name: Deploy Vite React to EC2

on:
  push:
    branches:
      - main
jobs:
  ec2deploy:
    runs-on: ubuntu-latest

    steps:
      - name: EC2서버에 접속하기
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            set -e

            APP_DIR=/home/ubuntu/vite-react-app
            REPO_URL="https://github.com/junhwan1310/react-docker1.git"
            DEV_PORT=5173

            if [! -d "$APP_DIR/.git"]; then
              sudo mkdir -p $APP_DIR
              sudo chown -R $USER:$USER $APP_DIR
              git clone $REPO_URL $APP_DIR
            fi

            cd $APP_DRI
            git checkout main
            git pull origin main

            npm ci

            ### Github Acitons 디플로이 파일 작성
```yaml
set -e
#변수 선언하기
APP_DIR=/home/ubuntu/vite-react-app
REPO_URL="https://github.com/junhwan1310/react-docker1.git"
DEV_PORT=5173
# 1) 최초 1회 clone하고 이후부터는 pull하기
if [! -d "$APP_DIR/.git"]; then
  sudo mkdir -p $APP_DIR
  sudo chown -R $USER:$USER $APP_DIR
  git clone $REPO_URL $APP_DIR
fi
cd $APP_DRI
git checkout main
git pull origin main
# 2)의존성 설치 -> package-locc.json기준
npm ci

# 3)기존 서버 종료(포트 기준으로 강제 kill하기)
# 실행 중이 아니더라도 실패하지 않도록 true옵션 추가
sudo fuser -k -n tcp ${DEV_PORT} || true

# 4)서버 백그라운드 기동
# --host 0.0.0.0 : 외부 접속 허용
# 로그는 dev.log파일로 저장
nohup npm run dev -- --host 0.0.0.0 --port ${DEV_PORT} > dev.log 2>&1 &

# 5)기동 확인(로그/포트 체크)
sleep 2
sudo fuser -n tcp ${DEV_PROT} || (ehco "server not running" && exit 1)
```